# Generated by Django 5.1.3 on 2025-01-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклами'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('main', 'Головна сторінка'), ('catalog', 'Каталог'), ('genres', 'Пошук за жанрами'), ('tags', 'Пошук за тегами'), ('fandoms', 'Пошук за фендомами')], max_length=20),
        ),
    ]
