# Generated by Django 5.1.3 on 2024-12-14 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('users', '0004_profile_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BalanceOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_type', models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Завершено'), ('failed', 'Помилка')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_operations', to='users.profile')),
            ],
            options={
                'verbose_name': 'Balance Operation Log',
                'verbose_name_plural': 'Balance Operation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
