# Generated by Django 5.1.3 on 2024-12-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_chapter_character_count_chapter_min_reading_time_and_more'),
        ('monitoring', '0002_alter_transactionlog_options_balanceoperationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('scroll_position', models.FloatField(default=0)),
                ('reading_time', models.IntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_progress', to='catalog.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогрес читання',
                'verbose_name_plural': 'Прогрес читання',
                'indexes': [models.Index(fields=['user', 'chapter'], name='monitoring__user_id_bba2fd_idx'), models.Index(fields=['is_read'], name='monitoring__is_read_a8bd6c_idx'), models.Index(fields=['is_purchased'], name='monitoring__is_purc_252af2_idx'), models.Index(fields=['user', 'is_read'], name='monitoring__user_id_e0e925_idx'), models.Index(fields=['user', 'is_purchased'], name='monitoring__user_id_847d11_idx'), models.Index(fields=['chapter', 'is_read'], name='monitoring__chapter_251720_idx')],
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
