# Generated by Django 5.1.3 on 2024-12-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_chapter_character_count_chapter_min_reading_time_and_more'),
        ('monitoring', '0003_userchapterprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapterprogress',
            name='reading_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userchapterprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='catalog.chapter'),
        ),
    ]
