# Generated by Django 5.1.3 on 2024-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_userchapterprogress_reading_speed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceoperationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Журнал операцій з балансом', 'verbose_name_plural': 'Журнал операцій з балансом'},
        ),
        migrations.AlterField(
            model_name='balanceoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('purchase', 'Покупка'), ('earning', 'Заробіток'), ('advertisement', 'Реклама'), ('refund', 'Повернення')], max_length=20),
        ),
        migrations.AlterField(
            model_name='balanceoperationlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершено'), ('failed', 'Помилка'), ('pending', 'В обробці')], max_length=20),
        ),
    ]
