# Generated by Django 5.1.3 on 2024-12-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_chapter_price'),
        ('monitoring', '0005_alter_balanceoperationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperationlog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення')], max_length=20),
        ),
        migrations.AlterField(
            model_name='balanceoperationlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершено'), ('failed', 'Помилка')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdvertisingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('main', 'Реклама на Головній'), ('genres', 'Реклама у Пошуку за жанрами'), ('tags', 'Реклама у Пошуку за тегами'), ('fandoms', 'Реклама у Пошуку за фендомами')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_logs', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал реклами',
                'verbose_name_plural': 'Журнал реклами',
                'ordering': ['-created_at'],
            },
        ),
    ]
