# Generated by Django 5.1.3 on 2025-08-31 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_chapter_price'),
        ('monitoring', '0006_alter_balanceoperationlog_operation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перегляд книги',
                'verbose_name_plural': 'Перегляди книг',
                'indexes': [models.Index(fields=['book', 'viewed_at'], name='monitoring__book_id_3546ed_idx'), models.Index(fields=['user', 'viewed_at'], name='monitoring__user_id_af179a_idx')],
            },
        ),
    ]
