# Generated by Django 5.1.3 on 2025-09-14 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_comment_book_permission_and_more'),
        ('monitoring', '0007_bookview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorThanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума подяки')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подяки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks_received', to='catalog.book', verbose_name='Книга')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_thanks', to=settings.AUTH_USER_MODEL, verbose_name='Хто подякував')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_thanks', to=settings.AUTH_USER_MODEL, verbose_name='Кому подякували')),
            ],
            options={
                'verbose_name': 'Подяка авторові',
                'verbose_name_plural': 'Подяки авторам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['giver', 'created_at'], name='monitoring__giver_i_5403b5_idx'), models.Index(fields=['receiver', 'created_at'], name='monitoring__receive_839da3_idx'), models.Index(fields=['book', 'created_at'], name='monitoring__book_id_fcda30_idx')],
            },
        ),
    ]
