# Generated by Django 5.1.3 on 2024-12-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_type', models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('purchase', 'Покупка'), ('earning', 'Заробіток')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В обробці'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='users.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
