# Generated by Django 5.1.3 on 2024-11-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_default_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Читач', 'Читач'), ('Перекладач', 'Перекладач')], default='Читач', max_length=20),
        ),
    ]
