# Generated by Django 5.1.3 on 2024-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Читач', 'Читач'), ('Перекладач', 'Перекладач')], default='Читач', max_length=20, verbose_name='Роль користувача'),
        ),
    ]
