# Generated by Django 5.1.3 on 2024-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_balancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Комісія (%)'),
        ),
    ]
