# Generated by Django 5.1.3 on 2024-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('purchase', 'Покупка'), ('earning', 'Заробіток'), ('advertisement', 'Реклама'), ('refund', 'Повернення')], max_length=20),
        ),
    ]
