# Generated by Django 5.1.3 on 2024-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_balancelog_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Поповнення'), ('withdraw', 'Виведення'), ('purchase', 'Покупка'), ('earning', 'Заробіток'), ('advertising', 'Реклама')], max_length=20),
        ),
    ]
