# Generated by Django 5.1.3 on 2025-02-08 11:13

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_balancelog_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='users/profile_images/no_image.jpg', null=True, upload_to=apps.users.models.Profile.get_upload_to),
        ),
    ]
