# Generated by Django 5.1.3 on 2025-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_confirmed',
            field=models.BooleanField(default=False, verbose_name='Підтверджено вік 18+'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chapter_comment_notifications',
            field=models.BooleanField(default=True, verbose_name='Сповіщення про коментарі до розділів'),
        ),
        migrations.AddField(
            model_name='profile',
            name='chapter_subscription_notifications',
            field=models.BooleanField(default=True, verbose_name='Сповіщення про передплату розділів'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comment_notifications',
            field=models.BooleanField(default=True, verbose_name='Сповіщення про коментарі'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_adult_content',
            field=models.BooleanField(default=False, verbose_name='Прибрати 18+ контент'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Сповіщення увімкнені'),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_messages_enabled',
            field=models.BooleanField(default=True, verbose_name='Приватні повідомлення'),
        ),
        migrations.AddField(
            model_name='profile',
            name='translation_status_notifications',
            field=models.BooleanField(default=True, verbose_name='Сповіщення про статус перекладу'),
        ),
    ]
