# Generated by Django 5.1.3 on 2025-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_image_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Читач', 'Читач'), ('Перекладач', 'Перекладач'), ('Літератор', 'Літератор')], default='Читач', help_text='Оберіть роль користувача. Роль визначає права доступу та можливості користувача.', max_length=20, verbose_name='Роль користувача'),
        ),
    ]
