# Generated by Django 5.1.3 on 2024-11-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_last_updated'),
        ('editors', '0002_errorreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение об ошибке', 'verbose_name_plural': 'Сообщения об ошибках'},
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.chapter'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='error_text',
            field=models.TextField(verbose_name='Текст с ошибкой'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='suggestion',
            field=models.TextField(verbose_name='Предложение по исправлению'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
