# Generated by Django 5.1.3 on 2024-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Повідомлення про помилку', 'verbose_name_plural': 'Повідомлення про помилки'},
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='error_text',
            field=models.TextField(verbose_name='Текст з помилкою'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='suggestion',
            field=models.TextField(verbose_name='Пропозиція щодо виправлення'),
        ),
    ]
