# Generated by Django 5.1.3 on 2024-11-30 19:08

import apps.catalog.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('author', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.book_image_path, verbose_name='Зображення книги')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('adult_content', models.BooleanField(default=False)),
                ('translation_status', models.CharField(choices=[('TRANSLATING', 'Перекладається'), ('WAITING', 'В очікуванні розділів'), ('PAUSED', 'Перерва'), ('ABANDONED', 'Покинутий')], default='TRANSLATING', max_length=20, verbose_name='Статус перекладу')),
                ('original_status', models.CharField(choices=[('ONGOING', 'Виходить'), ('STOPPED', 'Припинено'), ('COMPLETED', 'Завершений')], max_length=20, verbose_name='Статус випуску оригіналу')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.catalog.models.chapter_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('_position', models.DecimalField(db_column='position', decimal_places=1, default=0, max_digits=10)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('html_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Вартість глави')),
            ],
            options={
                'ordering': ['_position'],
            },
        ),
        migrations.CreateModel(
            name='ChapterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
