# Generated by Django 5.1.3 on 2024-11-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', 'XXXX_add_book_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Books_News',
            field=models.BooleanField(default=False),
        ),
    ]
