# Generated by Django 5.1.3 on 2024-11-25 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_book_books_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Books_News',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
    ]
