# Generated by Django 5.1.3 on 2024-11-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='chapterorder',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.chapter'),
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.country', verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='book',
            name='fandoms',
            field=models.ManyToManyField(to='catalog.fandom'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='catalog.genres'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalog.taggroups'),
        ),
        migrations.AddField(
            model_name='volume',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='chapterorder',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.volume'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='catalog.volume'),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('book', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterorder',
            unique_together={('volume', 'chapter')},
        ),
    ]
