# Generated by Django 5.1.3 on 2024-12-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='characters_count',
            field=models.IntegerField(default=0, verbose_name='Кількість символів'),
        ),
    ]
