# Generated by Django 5.1.3 on 2024-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_books_news_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення'),
        ),
    ]
