# Generated by Django 5.1.3 on 2024-12-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_chapter_characters_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('AUTHOR', 'Авторська'), ('TRANSLATION', 'Переклад')], default='TRANSLATION', max_length=20, verbose_name='Тип твору'),
        ),
    ]
