# Generated by Django 5.1.3 on 2024-11-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_last_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('book', 'title')},
        ),
        migrations.RemoveField(
            model_name='volume',
            name='slug',
        ),
    ]
