# Generated by Django 5.1.3 on 2024-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adult_content',
            field=models.BooleanField(default=False, verbose_name='Контент 18+'),
        ),
    ]
