# Generated by Django 5.1.3 on 2024-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_adult_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('TRANSLATING', 'Перекладається'), ('WAITING', 'В очікуванні розділів'), ('PAUSED', 'Перерва'), ('ABANDONED', 'Покинутий')], default='TRANSLATING', max_length=20, null=True, verbose_name='Статус перекладу'),
        ),
    ]
