# Generated by Django 5.1.3 on 2024-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_translation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translation_status',
            field=models.CharField(blank=True, choices=[('TRANSLATING', 'Перекладається'), ('WAITING', 'В очікуванні розділів'), ('PAUSED', 'Перерва'), ('ABANDONED', 'Покинутий')], max_length=20, null=True, verbose_name='Статус перекладу'),
        ),
    ]
