# Generated by Django 5.1.3 on 2024-12-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='character_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='min_reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
    ]
