# Generated by Django 5.1.3 on 2024-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_chapter_character_count_chapter_min_reading_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Вартість розділу'),
        ),
    ]
