# Generated by Django 5.1.3 on 2025-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_chapter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_book_permission',
            field=models.CharField(choices=[('all', 'Усі'), ('bookmarked', 'У кого в закладках'), ('none', 'Ніхто')], default='all', max_length=20, verbose_name='Коментувати книгу'),
        ),
        migrations.AddField(
            model_name='book',
            name='comment_chapter_permission',
            field=models.CharField(choices=[('all', 'Усі'), ('bookmarked', 'У кого в закладках'), ('none', 'Ніхто')], default='all', max_length=20, verbose_name='Коментувати розділ'),
        ),
        migrations.AddField(
            model_name='book',
            name='download_permission',
            field=models.CharField(choices=[('all', 'Усі'), ('bookmarked', 'У кого в закладках'), ('none', 'Ніхто')], default='all', max_length=20, verbose_name='Завантажити'),
        ),
        migrations.AddField(
            model_name='book',
            name='rate_permission',
            field=models.CharField(choices=[('all', 'Усі'), ('bookmarked', 'У кого в закладках'), ('none', 'Ніхто')], default='all', max_length=20, verbose_name='Оцінити'),
        ),
        migrations.AddField(
            model_name='book',
            name='view_permission',
            field=models.CharField(choices=[('all', 'Усі'), ('bookmarked', 'У кого в закладках'), ('none', 'Ніхто')], default='all', max_length=20, verbose_name='Увійти на сторінку книги'),
        ),
    ]
