# Generated by Django 5.1.3 on 2025-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_book_comment_book_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_status',
            field=models.CharField(choices=[('ONGOING', 'Виходить'), ('STOPPED', 'Припинено'), ('COMPLETED', 'Завершений')], default='ONGOING', max_length=20, verbose_name='Статус випуску оригіналу'),
        ),
    ]
