# Generated by Django 5.1.3 on 2025-01-02 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_alter_chapter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('book_ratings_count', models.IntegerField(default=0)),
                ('translation_ratings_count', models.IntegerField(default=0)),
                ('comment_likes_count', models.IntegerField(default=0)),
                ('bookmarks_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='catalog.book')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('book_ratings', models.IntegerField(default=0)),
                ('translation_ratings', models.IntegerField(default=0)),
                ('comment_likes', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='catalog.book')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='analytics_b_date_712cac_idx'), models.Index(fields=['book', 'date'], name='analytics_b_book_id_7ae8fe_idx')],
                'unique_together': {('book', 'date')},
            },
        ),
    ]
