# Generated by Django 5.1.3 on 2024-11-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_last_updated'),
        ('editors', '0003_alter_errorreport_options_alter_errorreport_book_and_more'),
        ('notification', '0002_notification_error_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='error_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editors.errorreport'),
        ),
    ]
