# Generated by Django 5.1.3 on 2024-11-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.bookcomment'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.chapter'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.chaptercomment'),
        ),
        migrations.AddField(
            model_name='chaptercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
